name: Deploy to Cloudflare Pages

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
    - cron: "0 7 3 * *"  # Every 3rd of every month at 2AM EST is 07:00 UTC
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloudflare Pages
        env:
          CF_DEPLOY_HOOK: ${{ secrets.CF_DEPLOY_HOOK }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${CF_DEPLOY_HOOK}"