name: Deploy to Cloudflare Pages

on:
  schedule:
    - cron: "0 2 * * 2"  # Every Tuesday at 02:00 UTC
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloudflare Pages
        env:
          CF_DEPLOY_HOOK: ${{ secrets.CF_DEPLOY_HOOK }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${CF_DEPLOY_HOOK}"